WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),

    # Password reset views
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    # Include the Django auth URLs for login/logout/password change
    path('accounts/', include('django.contrib.auth.urls')),
]

# Working with media files locally
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),

    # Book-related URLs
    path('books/', login_required(views.BookListView.as_view()), name='books'),
    path('books/<int:pk>/', login_required(views.BookDetailView.as_view()), name='book-detail'),
    path('book/create/', login_required(views.BookCreate.as_view()), name='book-create'),
    path('edit_books/', login_required(views.edit_books), name='edit-books'),
    path('book/update/<int:pk>/', login_required(views.BookUpdate.as_view()), name='book-update'),
    path('book/delete/<int:pk>/', login_required(views.BookDelete.as_view()), name='book-delete'),

    # Author-related URLs
    path('authors/', login_required(views.AuthorListView.as_view()), name='authors-list'),
    path('authors/<int:pk>/', login_required(views.AuthorDetailView.as_view()), name='authors-detail'),
    path('authors_add/', login_required(views.add_author), name='authors-add'),
    path('edit_authors/', login_required(views.edit_authors), name='edit-authors'),
    path('edit_author/<int:id>/', login_required(views.edit_author), name='edit-author'),
    path('delete_author/<int:id>/', login_required(views.delete_author), name='delete-author'),

    # User-specific URLs
    path('mybooks/', login_required(views.LoanedBooksByUserListView.as_view()), name='my-borrowed-books'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

@property
def is_overdue(self):
    if self.due_back and date.today() > self.due_back:
        return True
    return False

class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter the genre of the book",
                            verbose_name="Book Genre")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Enter the language of the book",
                            verbose_name="Book Language")

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Enter the publisher of the book",
                            verbose_name="Book Publisher")

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Enter the name of the author",
                                  verbose_name="Author Name")
    last_name = models.CharField(max_length=100,
                                 help_text="Enter the surname of the author",
                                 verbose_name="Author Surname")
    date_of_birth = models.DateField(help_text="Enter the date of birth",
                                     verbose_name="Birthday",
                                     null=True,
                                     blank=True)
    about = models.TextField(help_text="Enter the data about author",
                             verbose_name="About author")
    photo = models.ImageField(upload_to='images',
                              help_text="Upload author photo",
                              verbose_name="Author Photo",
                              null=True,
                              blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Enter the title of the book",
                             verbose_name="Book Title")
    genre = models.ForeignKey('Genre',
                              on_delete=models.CASCADE,
                              help_text="Enter the genre of the book",
                              verbose_name="Book Genre",
                              null=True)
    language = models.ForeignKey('Language',
                                 on_delete=models.CASCADE,
                                 help_text="Enter the language of the book",
                                 verbose_name="Book Language",
                                 null=True)
    publisher = models.ForeignKey('Publisher',
                                  on_delete=models.CASCADE,
                                  help_text="Enter the publisher of the book",
                                  verbose_name="Publisher",
                                  null=True)
    year = models.CharField(max_length=4,
                            help_text="Enter the year of the book",
                            verbose_name="Book Year")
    author = models.ManyToManyField('Author',
                                    help_text="Enter the author(s) of the book",
                                    verbose_name="Book Author(s)")
    summary = models.TextField(max_length=1000,
                               help_text="Enter the short summary of the book",
                               verbose_name="Book Annotation")
    isbn = models.CharField(max_length=13,
                            help_text="It must contain 13 symbols",
                            verbose_name="ISBN of the Book")
    photo = models.ImageField(upload_to="images",
                              help_text="Enter the cover of the book",
                              verbose_name="Book Cover")

    class Meta:
        ordering = ['title']  # Default ordering by book title

    def display_author(self):
        return ', '.join([f"{author.first_name} {author.last_name}" for author in self.author.all()])

    display_author.short_description = 'Authors'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Enter the status of the book instance",
                            verbose_name="Book Status")

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book',
                             on_delete=models.CASCADE,
                             null=True)
    inv_num = models.CharField(max_length=20,
                               null=True,
                               help_text="Enter the inventory number",
                               verbose_name="Inventory Number")
    status = models.ForeignKey('Status',
                               on_delete=models.CASCADE,
                               null=True,
                               help_text="Change the status of the book",
                               verbose_name='Status of the book')
    due_back = models.DateField(null=True,
                                blank=True,
                                help_text="Enter the due date",
                                verbose_name="Due date")
    borrower = models.ForeignKey(User,
                                 on_delete= models.SET_NULL,
                                 null=True,
                                 blank=True,
                                 verbose_name='Customer',
                                 help_text='Choose Customer',
                                 )

    class Meta:
        ordering = ["due_back"]

        def __str__(self):
            return '%s %s %s' % (self.inv_num, self.book, self.status)

catalog/forms.py
from django import forms
from datetime import date
from .models import Author, Book


# Form to add new authors to the database
class FormAddAuthor(forms.Form):
    first_name = forms.CharField(label="Author Name")
    last_name = forms.CharField(label="Author Surname")
    date_of_birth = forms.DateField(
        label="Birthdate",
        initial=format(date.today()),
        widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    about = forms.CharField(label="Data About Author", widget=forms.Textarea)
    photo = forms.ImageField(label="Author Photo")


class FormEditAuthor(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

catalog/views.py
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import render
from .models import Book, Author, BookInstance
from django.views.generic import ListView, DetailView
from .forms import FormAddAuthor, FormEditAuthor
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.views.generic.edit import CreateView, UpdateView, DeleteView



class AuthorDetailView(DetailView):
    model = Author


class AuthorListView(ListView):
    model = Author
    paginate_by = 5


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'


class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 5


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('edit-books')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = 'Create a New Book'
        return context


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('edit-books')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = 'Edit the Book'
        return context


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('edit-books')


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')


def index(request):
    # Get the list of books with pagination
    book_list = Book.objects.all()
    paginator = Paginator(book_list, 4)  # 4 books per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Calculate statistics
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()
    authors = Author.objects.all()
    num_authors = Author.objects.count()

    # Track visits to the site
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'page_obj': page_obj,
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'authors': authors,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }
    return render(request, 'catalog/index.html', context)


def about(request):
    text_head = "Data about Company"
    name = "Intellectual IT Systems"
    rab1 = "Software development based on AI"
    rab2 = "Recognizing road signs"
    rab3 = "Creation of art objects based on AI"
    rab4 = "Creation of digital interactive books, automated teaching systems"
    context = {
        'text_head': text_head,
        'name': name,
        'rab1': rab1,
        'rab2': rab2,
        'rab3': rab3,
        'rab4': rab4,
    }
    return render(request, 'catalog/about.html', context)


def contacts(request):
    text_head = "Contacts"
    name = "Intellectual IT Systems"
    address = "Gelvonu str. 35-20"
    telephone_number = "+37067178956"
    email = "dangluva@gmail.com"
    context = {
        'text_head': text_head,
        'name': name,
        'address': address,
        'telephone_number': telephone_number,
        'email': email,
    }
    return render(request, 'catalog/contacts.html', context)


def edit_author(request, id):
    author = Author.objects.get(id=id)
    # author = get_object_or_404(Author, pk=id)
    if request.method == 'POST':
        instance = Author.objects.get(pk=id)
        form = FormEditAuthor(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/edit_authors/')
    else:
        form = FormEditAuthor(instance=author)
        context = {
            'form': form,
        }
        return render(request, 'catalog/edit_author.html', context)


def edit_authors(request):
    authors = Author.objects.all()
    context = {
        'authors': authors,
    }
    return render(request, 'catalog/edit_authors.html', context)


# Creating new author in the database
def add_author(request):
    if request.method == "POST":
        form = FormAddAuthor(request.POST, request.FILES)
        if form.is_valid():
            # Get data from the form
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            date_of_birth = form.cleaned_data['date_of_birth']
            about = form.cleaned_data['about']
            photo = form.cleaned_data['photo']

            # Create and save the new author
            author = Author(
                first_name=first_name,
                last_name=last_name,
                date_of_birth=date_of_birth,
                about=about,
                photo=photo
            )
            author.save()
            # Redirect to the authors list view
            return HttpResponseRedirect(reverse('authors-list'))
    else:
        form = FormAddAuthor()

    context = {
        'form': form,
    }
    return render(request, 'catalog/authors_add.html', context)


# Deleting authors from the database
def delete_author(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect('/edit_authors/')
    except:
        return HttpResponseNotFound('<h2>Author is not found.</h2>')


def edit_books(request):
    book = Book.objects.all()
    context = {
        'book': book,
    }
    return render(request, 'catalog/edit_books.html', context)

templates/catalog/author_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container text-start">
    <div class="row my-3">
        <!-- Author Name Section -->
        <div class="col-12">
            <h4>{{ author.first_name }} {{ author.last_name }}</h4>
        </div>
    </div>

    <!-- Author Details Section -->
    <div class="row mb-4">
        <div class="col-12">
            <p><strong>Date of Birth:</strong> {{ author.date_of_birth|date:"F j, Y" }}</p>
        </div>
    </div>

    <!-- Photo Section -->
    <div class="row mb-4">
        <div class="col-12">
            <h5>Photo (portrait)</h5>
            {% if author.photo and author.photo.url %}
                <img src="{{ author.photo.url }}" alt="Portrait of {{ author.first_name }} {{ author.last_name }}" class="img-fluid" style="max-height: 200px;">
                <div class="mt-3">
                    <a href="{{ author.photo.url }}" class="btn btn-primary" target="_blank">View Full Image</a>
                </div>
            {% else %}
                <p class="text-muted">No photo available.</p>
            {% endif %}
        </div>
    </div>

    <!-- About Section -->
    <div class="row mb-4">
        <div class="col-12">
            <h5>About</h5>
            <div class="author-about">
                {{ author.about|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/authors_add.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4 text-center">Add Author to the Database</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered text-start w-100">
            {% for field in form %}
            <tr>
                <th style="width: 30%; vertical-align: middle; text-align: left;">
                    {{ field.label_tag }}
                </th>
                <td style="width: 70%;">
                    {% if field.name == 'photo' %}
                    <div class="d-flex align-items-center">
                        <!-- Display the existing photo if available -->
                        {% if author.photo and author.photo.url %}
                            <img src="{{ author.photo.url }}" alt="Photo of {{ author.first_name }} {{ author.last_name }}" class="img-thumbnail me-3" style="max-height: 100px;">
                        {% endif %}
                        <!-- File input (Choose button) -->
                        <div class="flex-grow-1">
                            {{ field }}
                        </div>
                    </div>
                    {% else %}
                    <!-- Render other fields normally -->
                    {{ field }}
                    {% endif %}
                    
                    <!-- Display errors for all fields -->
                    {% if field.errors %}
                    <div class="text-danger mt-1">
                        {% for error in field.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>

<style>
    /* Ensure all input fields occupy the full width of the table cell */
    input[type="text"],
    input[type="number"],
    input[type="email"],
    input[type="file"],
    input[type="date"],
    select,
    textarea {
        width: 100%; /* Ensures full width inside the table cell */
        box-sizing: border-box; /* Include padding and borders within the width */
    }

    /* Ensure the file input label (Author Photo) is left-aligned */
    td {
        text-align: left;
    }
</style>
{% endblock %}

templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Book Details: "{{ book.title }}"</h1>

    <table class="table table-bordered table-striped">
        <!-- Book Title and Author -->
        <tr>
            <th scope="row">Title</th>
            <td>{{ book.title }}</td>
        </tr>
        <tr>
            <th scope="row">Author(s)</th>
            <td>
                {% for author in book.author.all %}
                    <a href="{% url 'authors-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
        </tr>

        <!-- Book Cover -->
        <tr>
            <th scope="row">Cover</th>
            <td>
                {% if book.photo %}
                    <img src="{{ book.photo.url }}" alt="Cover of {{ book.title }}" class="img-fluid" style="max-height: 200px;">
                    <div class="mt-2">
                        <a href="{{ book.photo.url }}" class="btn btn-primary" target="_blank">View Full Cover</a>
                    </div>
                {% else %}
                    <span class="text-muted">No cover available</span>
                {% endif %}
            </td>
        </tr>

        <!-- Genre, ISBN, Language, and Publisher -->
        <tr>
            <th scope="row">Genre</th>
            <td>{{ book.genre }}</td>
        </tr>
        <tr>
            <th scope="row">ISBN</th>
            <td>{{ book.isbn }}</td>
        </tr>
        <tr>
            <th scope="row">Language</th>
            <td>{{ book.language }}</td>
        </tr>
        <tr>
            <th scope="row">Publisher</th>
            <td>{{ book.publisher }}</td>
        </tr>

        <!-- Book Summary -->
        <tr>
            <th scope="row">Annotation</th>
            <td>{{ book.summary }}</td>
        </tr>

        <!-- Book Instances -->
        {% if book.bookinstance_set.exists %}
            {% for copy in book.bookinstance_set.all %}
            <tr>
                <th scope="row">Inventory Number</th>
                <td>{{ copy.inv_num }}</td>
            </tr>
            <tr>
                <th scope="row">Status</th>
                <td>
                    <!-- Conditional styling based on status -->
                    {% include "catalog/book_status.html" %}
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <th scope="row">Copies Available</th>
                <td class="text-muted">No copies available.</td>
            </tr>
        {% endif %}

    </table>
</div>
{% endblock %}

templates/catalog/book_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% block head %}
<style>
    /* Ensure all input fields, textareas, and selects take full width of the table cell */
    input[type="text"],
    input[type="number"],
    input[type="email"],
    input[type="file"],
    select,
    textarea {
        width: 100%; /* Makes the input fields take the full width of the table cell */
        box-sizing: border-box; /* Include padding and borders within the width */
    }

    /* Ensure the file input and image are left-aligned */
    td {
        text-align: left; /* Ensures all table data cells have left-aligned content */
        vertical-align: middle; /* Vertically center the content */
    }

    /* Additional styling for images */
    img {
        max-height: 200px;
        display: block;
        margin: 0;
        padding: 0;
    }
</style>
{% endblock head%}


<div class="container mt-4">
    <!-- Use the context variable to display the correct heading -->
    <h2 class="mb-4">{{ heading }}</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered text-start">
            {% for field in form %}
            <tr>
                <th style="width: 30%; vertical-align: middle; text-align: left;">
                    {{ field.label_tag }}
                </th>
                <td style="width: 70%;">
                    {{ field }}
                    {% if field.errors %}
                    <div class="text-danger mt-1">
                        {{ field.errors }}
                    </div>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
{% endblock content%}

templates/catalog/book_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-4">
    <!-- Header Section -->
    <div class="row text-center text-dark mb-4">
        <h4>Book List in Database</h4>
    </div>

    <!-- Book List -->
    {% if books %}
    <table class="table table-striped table-bordered text-center">
        <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th>Cover</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
        <tr>
            <!-- Link to book details using Django's url template tag -->
            <td class="align-middle"><a href="{% url 'book-detail' book.id %}">{{ book.title }}</a></td>
            <td class="align-middle">{{ book.display_author }}</td>
            <td class="align-middle">{{ book.genre.name }}</td>
            <td class="align-middle">
                {% if book.photo %}
                <!-- Use a container with fixed dimensions for the image -->
                <div style="width: 100px; height: 150px; margin: 0 auto;">
                    <img src="{{ book.photo.url }}" alt="Cover of {{ book.title }}" class="img-fluid" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                {% else %}
                <span class="text-muted">No cover available</span>
                {% endif %}
            </td>
            <td class="align-middle">
               <!-- Book Instances -->
            {% if book.bookinstance_set.exists %}
                <ul class="list-unstyled">
                    {% include "catalog/book_status.html" %}
                </ul>
            {% else %}
                <p class="text-muted">No copies available for this book.</p>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="text-muted text-center">There are no books in the database.</p>
    {% endif %}
</div>

<style>
    /* Ensure all table cells are vertically centered */
    .table td, .table th {
        vertical-align: middle; /* Vertically center content in all table cells */
    }

    /* Center images in the table cells */
    .img-fluid {
        display: block;
        margin: 0 auto; /* Horizontally center images */
    }
</style>
{% endblock %}

templates/catalog/book_status.html
<!-- catalog/templates/catalog/_book_status.html -->
{% for copy in book.bookinstance_set.all %}
    <ul class="list-unstyled">
        <!-- Conditional styling based on status -->
        {% if copy.status.name == "Sold" %}
            <span style="color: red; font-weight: bold;">{{ copy.status.name }}</span>
        {% elif copy.status.name == "Ordered" %}
            <span style="color: blue; font-weight: bold;">{{ copy.status.name }}</span>
        {% elif copy.status.name == "Available" %}
            <span style="color: green; font-weight: bold;">{{ copy.status.name }}</span>
        {% endif %}
    </ul>
{% endfor %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Borrowed Books</h1>

    {% if bookinstance_list %}
        <div class="row">
            {% for bookinst in bookinstance_list %}
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow-sm">
                    <div class="card-body d-flex flex-column">
                        <!-- Book Title -->
                        <a href="{% url 'book-detail' bookinst.book.pk %}" class="text-decoration-none">
                            <h5 class="card-title">{{ bookinst.book.title }}</h5>
                        </a>

                        <!-- Book Due Date -->
                        <p class="card-text">Due back on: <strong>{{ bookinst.due_back|date:"F j, Y" }}</strong></p>

                        <!-- Overdue Status with Icon -->
                        {% if bookinst.is_overdue %}
                            <p class="text-danger"><i class="fa fa-exclamation-triangle"></i> Overdue!</p>
                        {% else %}
                            <p class="text-success"><i class="fa fa-check-circle"></i> On time</p>
                        {% endif %}

                        <!-- Status with Conditional Coloring and Icon -->
                        <div class="mt-auto">
                            <p class="card-text">
                                <strong>Status:</strong> 
                                {% if bookinst.status.name == "Sold" %}
                                    <span style="color: red; font-weight: bold;"><i class="fa fa-times-circle"></i> {{ bookinst.status.name }}</span>
                                {% elif bookinst.status.name == "Ordered" %}
                                    <span style="color: blue; font-weight: bold;"><i class="fa fa-truck"></i> {{ bookinst.status.name }}</span>
                                {% else %}
                                    <span style="color: green; font-weight: bold;"><i class="fa fa-book"></i> {{ bookinst.status.name }}</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">No Borrowed Books</h4>
            <p>You currently do not have any borrowed books.</p>
            <hr>
            <p class="mb-0">Browse available books in our <a href="{% url 'books' %}">catalog</a>.</p>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/catalog/edit_author.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Edit Author Information</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered text-start">
            {% for field in form %}
            <tr>
                <th style="width: 30%; vertical-align: middle; text-align: left;">
                    {{ field.label_tag }}
                </th>
                <td style="width: 70%;">
                    <div style="width: 100%;">
                        {{ field }}
                    </div>
                    {% if field.errors %}
                    <div class="text-danger mt-1">
                        {{ field.errors }}
                    </div>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
    </form>
</div>

<style>
    /* Ensure all input fields occupy the full width of the table cell */
    input[type="text"],
    input[type="number"],
    input[type="email"],
    input[type="file"],
    input[type="date"],  /* Added date input style */
    select,
    textarea {
        width: 100%; /* Ensures full width inside the table cell */
        box-sizing: border-box; /* Include padding and borders within the width */
    }

    /* Ensure the file input label (Author Photo) is left-aligned */
    td {
        text-align: left;
    }
</style>
{% endblock %}